# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-06 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='topic',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='forum.Topic', verbose_name='Tópico'),
            preserve_default=False,
        ),
    ]
