# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_reply_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default=1, max_length=100, unique=True, verbose_name='Identificador'),
            preserve_default=False,
        ),
    ]
