# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170203_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='País')),
                ('city', models.CharField(max_length=30, verbose_name='Cidade')),
                ('state', models.CharField(max_length=30, verbose_name='Estado')),
                ('complement', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
            ],
            options={
                'verbose_name': 'Endereço',
                'verbose_name_plural': 'Endereços',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DDD', models.IntegerField(verbose_name='DDD')),
                ('number', models.IntegerField(verbose_name='Número')),
            ],
            options={
                'verbose_name': 'Telefone',
                'verbose_name_plural': 'Telefones',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Nome'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address', verbose_name='Endereço'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.Phone', verbose_name='Telefone'),
            preserve_default=False,
        ),
    ]
