# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-07 03:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20170207_0350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Address', verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Phone', verbose_name='Telefone'),
        ),
    ]
